version: "3.8"

services:
  frontend:
    image: 17med/jobportalfrontend:test
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    networks:
      - projectnet

  backend:
    image: 17med/jobportalbackend:test
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - projectnet

networks:
  projectnet:
    driver: bridge
