version: "3.8"

services:
  frontend:
    image: 17med/jobportalfrontend:latest
    ports:
      - "80:80"
    networks:
      - my-network

  backend:
    image: 17med/jobportalbackend:latest
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
